apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-affinity-deploy3
spec:
  replicas: 2
  minReadySeconds: 5
  selector:
    matchLabels:
      app: hospital-backend
  template:
    metadata:
      labels:
        app: hospital-backend
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - hospital-frontend
                topologyKey: kubernetes.io/hostname
      containers:
        - name: hospital
          image: nginx:latest
          ports:
            - containerPort: 80
